### ISSUE TITLE
Statsystem

### ISSUE THREAD

**Issue by LuckyDjuk** [nexiuhm/HealingSim-ES6#19]
Stats, add character pane, UI/style later. Consider iLVL here

Base attributes (agi, stam, int, str, spi)
Secondary attributes (haste_rating, mastery_rating, crit_rating and so forth)
Mana - Based on class and level for now. (Consider that it scaled with int before WoD), example on class is that if player is resto/holy gain a hidden aura that increases the mana pool by 400%.

Mastery - Calculated from Mastery_rating
Block - Stat for warrior/paladin
Parry - Stat for warrior/paladin. Everyone have 5% as base.

**Comment by nexiuhm** [comment]
Maybe we we can create a stat class? That entity will have.

 In the Player constructor   we can register special stats  that only exists for players, like  `stats.add("mastery", args..)`
I believe base stats + defensive stats are true for both players and bosses

Consider that we need to kill the player when health gets to 0, we could do something like `stats.health.onMinValue( function () { this.player.alive = false }`

That way alot of complexity is moved away from the actual class. Either that or we keep all the complexity in the enitity base class.

**Comment by nexiuhm** [comment]
Added something like this in the lastest commit. Stats are now objects that takes care of their own min / max value, since this logic was reapated all over the place in unit.es6
