### ISSUE TITLE
Aura & action system

### ISSUE THREAD

**Issue by LuckyDjuk** [nexiuhm/HealingSim-ES6#20]
Add a list of names of buffs that a player can have. Prepare for debuffs. Add color on players who have buff/debuff.

**Comment by nexiuhm** [comment]
Adding some notes here.

So buffs/auras can be boiled down to "something that modifies the current state of the enitity, usually temporary" 

To name a few (in capslock of course):

APPLY_DIRECT_DAMAGE  ( not really an aura/buff but an action ?)
APPLY_AURA_MODIFIER ( +20% armor f.ex )
APPLY_AURA_PERIODIC_HEAL ( heals the player for X amount on an interval over Y amount of time)

¨
Some things to consider:
- Where should auras be stored ( on the root of the entity class? as in entity.aura)
- How will auras be created?  i.e  new Aura("PERIODIC_HEAL" , arg1 , arg2 ) 
- Who is responsible for creating the aura ? Enitiy class ? spell class? action handler?

**Comment by nexiuhm** [comment]
Basic stuff is in place.  Periodic auras not implemented yet
