### ISSUE TITLE
Event system

### ISSUE THREAD

**Issue by LuckyDjuk** [nexiuhm/HealingSim-ES6#21]
Make a class that handles events. Prepare listeners from a specific player. Consider adding this in player too, as in player listening for events during boss encounter

**Comment by nexiuhm** [comment]
We should decide if we should build this using Phasers internal event emitter system ( like we are now ) Or maybe find a nicer library specifically for this?

Either way, let's put up a list of  features this event system could contain:
-  Subsribe to specific sub-events ( not really sure what to call it ), like the event would be HEALTH_CHANGED and the subevent would be PLAYER_ID.  ( maybe some library already supports something similar to this ? )

**Comment by nexiuhm** [comment]
Cosmetic improvement. Low prio

**Comment by nexiuhm** [comment]
Phaser already has a event system that we can use for now.
