### ISSUE TITLE
Base class for entity

### ISSUE THREAD

**Issue by LuckyDjuk** [nexiuhm/HealingSim-ES6#37]
Setup base/super class for players, NPC and boss. Contains Aura/action system, Stat system, Spell component and Action Handler.

**Comment by nexiuhm** [comment]
Huge undertaking, in a sense this is pretty much the core of the whole game. We need to look at the bigger picture here and have some idea of how stats, auras, actions / spells will fit together nicely. Boring task, but when all this is in place the more fun part begins, making UI improvements, implementing classes and spells easily etc etc.
