### ISSUE TITLE
Menu state

### ISSUE THREAD

**Issue by LuckyDjuk** [nexiuhm/HealingSim-ES6#38]
Add ability to select boss and class. Unavailable classes are greyed out.

**Comment by nexiuhm** [comment]
First of all we should decide if we should do this in phaser or HTML. HTML will be alot easier I can imagine but feels more correct to just do everything in Phaser?

To implement this in Phaser :
-   We need buttons, I believe this is already included in Phaser and we can probably just style them the way we want. ¨
- The idea of button "groups" ( kind of like radio-buttons in HTML where you can only select 1 option and if you select a new option the older one will be deselected )
- Whatever is selected in the screen should be written to a json-type variable, so the play state can parse it.
- Input validation for some stuff ( playername maybe? regular expressions should work nicely here )
- Text input field ( dont think phaser have anything like this so lets think about how to make it )

First iteration goal:
- Select boss
- Select class
- Difficulty

How do we get the data to the play state?:
- Its possible to send parameters when starting a state `game.state.start('Play', true, false, customParam1, customParam2etc);` These parameters will be recived by the state init() function.
- We can write the data to somewhere in data.ts and then retrieve it in the mainstate.

**Comment by nexiuhm** [comment]
Created a concept to work from. Please come with feedback of dislikes with the current plan. 

 Kind of scrapped the idea of having a player name for now . Reasons:
-  Most people probably don't care.
-  It's hours of work for a small detail ( if implementing in webgl & we have little xp with webgl) 
- I've already made a PR to Phaser to deal with this specific problem and hoping it will go through,
-  Doesn't really add anything to the gameplay
- Doesn't fit with our approach of "minimal working version"

So the idea atm is to have simple "multiple-choice" type config options  before starting the game.  Having custom player names makes more sense for version 2 - when importing from armory etc.
